export const baseURL = "https://be-node.onrender.com/"

export const homeURL = "/"
export const productsURL = "/products"
export const productDetailURL = "/products/:idProduct"
export const loginURL = "/login"
export const registerURL = "/register"
export const cartURL = "/cart"
export const profileURL = "/profile"
export const blogURL = "/blog"
export const aboutURL = "/about"
export const contactURL = "/contact"

export const adminHomeURL = "/admin"
export const adminProductURL = "/admin/products"
export const adminUserURL = "/admin/user"
