export const GET_KEY_SEARCH = "KEY_SEARCH";
export const GET_PRODUCT_BY_KEY_SEARCH_SUCCESS =
  "GET_PRODUCT_BY_KEY_SEARCH_SUCCESS";
export const GET_TOTAL_ITEM = "GET_TOTAL_ITEM";
export const GET_PAGE_NUMBER = "GET_PAGE_NUMBER";
export const GET_PAGE_LIMIT_NUMBER = "GET_PAGE_LIMIT_NUMBER";
export const SORT_PRODUCT = "SORT_PRODUCT";
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY";
export const GET_SIZE_PRODUCT = "GET_SIZE_PRODUCT";
export const GET_COLOR_PRODUCT = "GET_COLOR_PRODUCT";
export const GET_RATING_PRODUCT = "GET_RATING_PRODUCT";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
