export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const GET_PRODUCT_LIST_LATEST = "GET_PRODUCT_LIST_LATEST";
export const GET_PRODUCT_LIST_LATEST_SUCCESS =
  "GET_PRODUCT_LIST_LATEST_SUCCESS";
export const GET_PRODUCT_LIST_LATEST_ERROR = "GET_PRODUCT_LIST_LATEST_ERROR";

export const GET_PRODUCT_LIST_COMING = "GET_PRODUCT_LIST__COMING";
export const GET_PRODUCT_LIST_COMING_SUCCESS =
  "GET_PRODUCT_LIST_COMING_SUCCESS";
export const GET_PRODUCT_LIST_COMING_ERROR = "GET_PRODUCT_LIST_COMING_ERROR";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_ID_PRODUCT = "GET_ID_PRODUCT";
