export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const GET_PRODUCT_LIST_LATEST = "GET_PRODUCT_LIST_LATEST";
export const GET_PRODUCT_LIST_LATEST_SUCCESS =
  "GET_PRODUCT_LIST_LATEST_SUCCESS";
export const GET_PRODUCT_LIST_LATEST_ERROR = "GET_PRODUCT_LIST_LATEST_ERROR";

export const GET_PRODUCT_LIST_COMING = "GET_PRODUCT_LIST__COMING";
export const GET_PRODUCT_LIST_COMING_SUCCESS =
  "GET_PRODUCT_LIST_COMING_SUCCESS";
export const GET_PRODUCT_LIST_COMING_ERROR = "GET_PRODUCT_LIST_COMING_ERROR";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_ID_PRODUCT = "GET_ID_PRODUCT";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const CLEARE_MESSAGE_PRODUCT = "CLEARE_MESSAGE_PRODUCT";
