export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const GET_PROFILE_USER = "GET_PROFILE_USER";

export const USER_LOG_OUT = "USER_LOG_OUT";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const UPDATE_QUANTITY_CART_ITEM = "UPDATE_QUANTITY_CART_ITEM";

export const SEND_LIST_PAYMENT = "SEND_LIST_PAYMENT";
export const GET_LIST_PAYMENT_USER = "GET_LIST_PAYMENT_USER";
export const GET_LIST_PAYMENT_USER_SUCCESS = "GET_LIST_PAYMENT_USER_SUCCESS";
