export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_REGISTER = "USER_REGISTER";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const GET_PROFILE_USER = "GET_PROFILE_USER";
export const GET_PROFILE_USER_SUCCESS = "GET_PROFILE_USER_SUCCESS";
export const UPDATE_PROFILE_USER = "UPDATE_PROFILE_USER";
export const UPDATE_PROFILE_USER_SUCCESS = "UPDATE_PROFILE_USER_SUCCESS";
export const UPDATE_PROFILE_USER_FAILURE = "UPDATE_PROFILE_USER_FAILURE";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const DELETE_LIST_CART_ORDERED = "DELETE_LIST_CART_ORDERED";
export const UPDATE_QUANTITY_CART_ITEM = "UPDATE_QUANTITY_CART_ITEM";

export const SEND_LIST_PAYMENT = "SEND_LIST_PAYMENT";
export const GET_LIST_PAYMENT_USER = "GET_LIST_PAYMENT_USER";
export const GET_LIST_PAYMENT_USER_SUCCESS = "GET_LIST_PAYMENT_USER_SUCCESS";

export const ADD_A_REVIEW = "ADD_A_REVIEW";
export const ADD_A_REVIEW_SUCCESS = "ADD_A_REVIEW_SUCCESS";
export const GET_REVIEW_OF_PRODUCT = "GET_REVIEW_OF_PRODUCT";
export const GET_REVIEW_OF_PRODUCT_SUCCESS = "GET_REVIEW_OF_PRODUCT_SUCCESS";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS";

export const SEARCH_USER = "SEARCH_USER";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";

export const CLEARE_MESSAGE_USER = "CLEARE_MESSAGE_USER";
